testing/cocoon: skip test on loongarch64
The TestSubscribeReposFutureCursorStaysLive test failed on the
loongarch64 builder despite retries and increased ticker timeout.

```
--- FAIL: TestSubscribeReposFutureCursorStaysLive (5.46s)
    subscribe_repos_test.go:685: read message: websocket: close 1001 (going away)
2026/10/07 20:32:04 ERROR failed to persist outbound event system=events err="failed to persist event: disk I/O error: no such file or directory"
2026/10/07 20:32:04 ERROR failed to persist outbound event system=events err="failed to persist event: attempt to write a readonly database"
2026/10/07 20:32:04 ERROR events playback system=events err="failed to query events: context canceled"
2026/10/07 20:32:05 ERROR events playback system=events err="failed to query events: context canceled"
FAIL
FAIL	github.com/haileyok/cocoon/server	148.959s
```

Possibly related to test update in 0.13.0.
https://github.com/haileyok/cocoon/commit/da70ffd7954e8a9d870f40b3606249aec330d7f0